name: crm
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=3.2.3 <4.0.0'
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    cupertino_icons: ^1.0.2
    get: ^4.6.1
    get_storage: ^2.0.3
    http: ^1.1.2
    shared_preferences: ^2.0.8
    flutter_local_notifications: ^16.2.0
    intl: ^0.18.1
    auto_size_text: ^3.0.0
    json_theme: ^6.4.0
    flutter_expandable_fab: ^2.0.0
    sqflite: ^2.3.0
    path: ^1.8.3
    syncfusion_flutter_calendar: ^24.1.44

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/font/Almarai-Bold.ttf
        - asset: assets/font/Almarai-ExtraBold.ttf
        - asset: assets/font/Almarai-Light.ttf
        - asset: assets/font/Almarai-Regular.ttf
